### ISSUE TITLE
Profanity not responding to input/connecting

### ISSUE THREAD

**Issue by Endraig** [matt-lowe/ProfanityFE#5]
, having issues running profanity on win10 with cmder. I have the headless lich set up and working, it logs my character into the game but when i run my .bat file for profanity it loads up the FE but doesnt show any scroll and does not respond to the first command input, and upon hitting any key after such the window closes immediately. 

this is the error in the profanity log:

string contains null byte
C:/Profanity/profanity.rb:74:in `addstr'
C:/Profanity/profanity.rb:74:in `block in add_line'
C:/Profanity/profanity.rb:70:in `each'
C:/Profanity/profanity.rb:70:in `add_line'

please help i've checked my firewall/ports/admin rights/fonts/colors not sure what else to look at.

**Comment by sandersch** [comment]
GitHub issues are for developer discussion and not for user support.

If you need help setting up Lich, you will probably have much better luck on the [Lich Topic of the GS4 Player's Corner Forum](http://forum.gsplayers.com/forumdisplay.php?104-The-Lich-Project).
