### ISSUE TITLE
curses (LoadError) ?

### ISSUE THREAD

**Issue by elBlanquito** [matt-lowe/ProfanityFE#9]
I'm getting this error when trying to run profanityFE on ubuntu 16.04, is this an issue you can immediately identify? I don't know how to squash it:

user@computer-desktop:~/lich$ sudo ruby profanity.rb --port=8001
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- curses (LoadError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from profanity.rb:32:in `<main>'
user@computer-desktop:~/lich$

**Comment by elBlanquito** [comment]
The gem curses literally wasn't installed in my local environment, once I did that and followed the error after that, not having a defined log_file, back to lines 442-465ish where the actual arguments accepted are explicitly listed I was able to get it running. Marvelous! I started an epedia page for your project just with those argument variables because they are infinitely useful to be able to reference. Thank you for the project, look forward to offering forward some pulls!
